[target]
programs=httpget

[require]
packages=indy
packagedir=../../

[compiler]
unittargetdir=units/$(CPU_TARGET)-$(OS_TARGET)
unitdir=../../System/lib/$(CPU_TARGET)-$(OS_TARGET):\
        ../../Core/lib/$(CPU_TARGET)-$(OS_TARGET):\
        ../../Protocols/lib/$(CPU_TARGET)-$(OS_TARGET):\
        ../../
options=-gl

[install]
fpcpackage=y
